blueprint:
  name: Voice - File Content Analyzer (Fixed Camera Source)
  author: luuquangvu + modified by DoThai
  description: >-
    Tool designed to analyze and extract all types of information from media and document files.
  domain: script
  homeassistant:
    min_version: 2025.8.0

  input:
    entity_aliases_settings:
      name: Settings for Entity Aliases
      icon: mdi:format-list-bulleted
      input:
        entity_aliases:
          name: Entity Aliases
          selector:
            entity:
              filter:
                - domain: sensor
                  integration: template

    ai_task_settings:
      name: Settings for AI Task
      icon: mdi:robot-outline
      collapsed: true
      input:
        value_template: "{{ not instructions }}"

sequence:
  - alias: Validate instructions
    if:
      - condition: template
        value_template: "{{ not instructions }}"
    then:
      - variables:
          response:
            error: "Unable to extract data because instructions is missing or incorrect."
      - stop: "Unable to extract data because instructions is missing or incorrect."
        response_variable: response

  - alias: Validate media source
    if:
      - condition: template
        value_template: "{{ not media_source in ['camera', 'path'] }}"
    then:
      - variables:
          response:
            error: "Unable to extract data because media source is missing or incorrect."
      - stop: "Unable to extract data because media source is missing or incorrect."
        response_variable: response

  - alias: Validate mime type
    if:
      - condition: template
        value_template: "{{ not mime_type.startswith(('image/', 'video/', 'audio/', 'text/', 'application/')) }}"
    then:
      - variables:
          response:
            error: "Unable to extract data because MIME type is missing or incorrect."
      - stop: "Unable to extract data because MIME type is missing or incorrect."
        response_variable: response

  ########################################################################
  # ✅ SỬA ĐÚNG THEO YÊU CẦU: SỬ DỤNG media-source://camera/{{ final_camera }}
  ########################################################################
  - alias: Process camera media
    if:
      - condition: template
        value_template: "{{ media_source == 'camera' }}"
    then:
      - variables:
          final_camera: >-
            {% if (states.camera | selectattr('attributes.friendly_name', '==', media_path.strip()) | list) %}
            {{ states.camera | selectattr('attributes.friendly_name', '==', media_path.strip()) | map(attribute='entity_id') | first }}
            {% else %}
            {{ state_attr(entity_aliases, 'entities') | default([]) | selectattr('entity_id', 'match', 'camera\.') | selectattr('aliases', 'contains', media_path.strip()) | map(attribute='entity_id') | first }}
            {% endif %}

      - variables:
          attachments:
            media_content_id: media-source://camera/{{ final_camera }}
            media_content_type: "{{ mime_type }}"

    else:
      - alias: Process file media
      - if:
          - condition: template
            value_template: "{{ media_path.startswith(('media-source', '/')) or not '/' in media_path }}"
        then:
          - variables:
              response:
                error: "Unable to extract data because media path is incorrect."
          - stop: "Unable to extract data because media path is incorrect."
            response_variable: response
      - variables:
          attachments:
            media_content_id: "media-source://media_source/{{ media_path }}"
            media_content_type: "{{ mime_type }}"

  ########################################################################
  # CALL AI TASK
  ########################################################################
  - alias: Run AI Task
    choose:
      - conditions:
          - condition: template
            value_template: "{{ not ai_task_entity }}"
        sequence:
          - action: ai_task.generate_data
            data:
              task_name: Analyze content from a media entity
              instructions: "{{ instructions }}"
              attachments: "{{ attachments }}"
            response_variable: result
    default:
      - action: ai_task.generate_data
        data:
          task_name: Analyze content from a media entity
          instructions: "{{ instructions }}"
          attachments: "{{ attachments }}"
          entity_id: "{{ ai_task_entity }}"
        response_variable: result

  - variables:
      response:
        data: "{{ result.data }}"

  - stop: ""
    response_variable: response
