blueprint:
  name: Voice - File Content Analyzer
  author: DoThai
  description: >-
    Chụp ảnh từ camera, lưu vào /media/ai_task/image/<ngày>, rồi gửi đúng metadata cho AI Task.
  domain: script
  homeassistant:
    min_version: 2025.8.0

  input:
    ai_task_entity:
      name: AI Task Entity
      description: "Entity của AI Task (ví dụ: ai_task.gemini_2_5_flash_ai_task)"
      selector:
        entity:
          filter:
            domain: ai_task
    camera_entity:
      name: Camera Entity
      description: "Camera để chụp ảnh snapshot"
      selector:
        entity:
          filter:
            domain: camera
    instructions_prompt:
      name: Hướng dẫn phân tích
      description: "Mô tả nội dung muốn AI phân tích"
      selector:
        text:
          multiline: true
      default: "Phân tích hình ảnh ngắn gọn."

mode: parallel
max_exceeded: silent

sequence:
  - variables:
      ai_task_entity: !input ai_task_entity
      camera_entity: !input camera_entity
      instructions: !input instructions_prompt
      today: "{{ now().strftime('%Y-%m-%d') }}"
      filename: "{{ today }}_{{ now().strftime('%H-%M-%S') }}.jpg"
      folder_path: "/media/ai_task/image/{{ today }}"
      file_path: "{{ folder_path }}/{{ filename }}"
      media_source_path: "media-source://media_source/ai_task/image/{{ today }}/{{ filename }}"

  # 📸 Chụp ảnh camera
  - service: camera.snapshot
    data:
      entity_id: "{{ camera_entity }}"
      filename: "{{ file_path }}"

  # 🧠 Gửi ảnh tới AI Task để phân tích
  - service: ai_task.generate_image
    data:
      task_name: "Camera Snapshot Analysis"
      instructions: "{{ instructions }}"
      entity_id: "{{ ai_task_entity }}"
      attachments:
        media_content_id: "{{ media_source_path }}"
        media_content_type: "image/jpeg"
        metadata:
          title: "{{ filename }}"
          thumbnail: null
          media_class: "image"
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: "app"
              media_content_id: "media-source://media_source"
            - media_content_type: ""
              media_content_id: "media-source://media_source/ai_task"
            - media_content_type: ""
              media_content_id: "media-source://media_source/ai_task/image"
            - media_content_type: ""
              media_content_id: "media-source://media_source/ai_task/image/{{ today }}"

  - log_message:
      level: info
      message: "Ảnh '{{ filename }}' đã được gửi tới {{ ai_task_entity }} thành công!"
