blueprint:
  name: Voice - File Content Analyzer
  author: DoThai1
  description: >
    Phân tích hình ảnh trực tiếp từ camera được truyền vào khi gọi script (không cần lưu file).
  domain: script
  homeassistant:
    min_version: 2025.8.0

  input:
    ai_task_entity:
      name: AI Task Entity
      description: "Entity của AI Task (ví dụ: ai_task.gemini_2_5_flash_ai_task)"
      selector:
        entity:
          filter:
            domain: ai_task

    instructions_prompt:
      name: Instructions
      description: "Mô tả yêu cầu AI cần thực hiện."
      selector:
        text:
          multiline: true
      default: "Phân tích xem có người trong khung hình hay không"

mode: parallel
max_exceeded: silent

fields:
  camera_entity:
    name: Camera Entity
    description: "Camera cần phân tích (truyền khi gọi script)"
    selector:
      entity:
        filter:
          domain: camera
    required: true

  instructions:
    name: Instructions
    description: "Yêu cầu AI (ghi đè nếu muốn)"
    selector:
      text:
        multiline: true

sequence:
  - variables:
      ai_task_entity: !input ai_task_entity
      camera_entity: "{{ camera_entity }}"
      instructions: "{{ instructions or instructions_prompt }}"
  
  # ✅ Kiểm tra camera hợp lệ
  - if:
      - condition: template
        value_template: "{{ camera_entity is defined and camera_entity | length > 0 }}"
    then:
      - variables:
          snapshot_url: "{{ state_attr(camera_entity, 'entity_picture') or '/api/camera_proxy/' ~ camera_entity }}"
    else:
      - stop: "Thiếu camera entity hoặc không hợp lệ."

  # ✅ Gọi AI Task xử lý ảnh trực tiếp từ camera
  - service: ai_task.generate_data
    data:
      task_name: "Analyze camera frame"
      instructions: "{{ instructions }}"
      attachments:
        - media_content_id: "http://homeassistant.local:8123{{ snapshot_url }}"
          media_content_type: "image/jpeg"
      entity_id: "{{ ai_task_entity }}"
    response_variable: result

  - variables:
      response: "{{ result.data | default('Không có phản hồi từ AI.') }}"

  - stop: "{{ response }}"
