blueprint:
  name: Voice - File Content Analyzer
  author: Thaidv
  description: >-
    # Tool designed to analyze and extract all types of information from media and document files

    ## Blueprint Setup

    ### Required

    * An AI Task entity must be created and configured in the System - General settings.

    ### Optional

    * Adjust the prompts for each field used in the script. The descriptions guide the LLM to provide the correct input.

    ### Note

    * Provide a concise and precise description for the script. This description will enable the LLM to recognize that the script is designed to extract data from a media or document file.

    * Make sure to expose the script to Assist after the script has been saved.

    * Do not alter the default script name.
  domain: script
  homeassistant:
    min_version: 2025.8.0
  input:
    ai_task_settings:
      name: Settings for AI Task
      icon: mdi:robot-outline
      description: These settings allow you to set up the AI Task responsible for handling the analyzer task.
      collapsed: true
      input:
        ai_task_entity:
          name: AI Task Entity
          description: If left empty, the system will use the default settings under System - General.
          selector:
            entity:
              filter:
                domain: ai_task
          default:
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        instructions_prompt:
          name: Instructions Prompt
          description: The prompt which will be used for the LLM can provide the request for the query.
          selector:
            text:
              multiline: true
          default: >-
            This argument is mandatory and must always be provided.

            The tool can analyze content and extract any type of information from an image, video, audio, or document, including text, numbers, objects, speech, and visual features.

            Always clearly specify exactly what data should be extracted.
        image_path_prompt:
          name: Image Path Prompt
          description: The prompt which will be used for the LLM to provide the image URL/path.
          selector:
            text:
              multiline: true
          default: >-
            This argument is mandatory and must always be provided. Select the correct camera and provide the full URL for the image you want to analyze. Available cameras and their URLs: - Kho: http://localhost:1984/api/frame.jpeg?src=camera.ezvizkho - Cổng: http://localhost:1984/api/frame.jpeg?src=camera.ezvizcong - Sân: http://localhost:1984/api/frame.jpeg?src=camera.ezvizsan - Phòng Khách: http://localhost:1984/api/frame.jpeg?src=camera.pkhach Only enter the URL that matches the camera you want to analyze. Example: If you want to analyze an image from 'san', enter http://localhost:1984/api/frame.jpeg?src=camera.ezvizsan
        mime_type_prompt:
          name: MIME Type Prompt
          description: The prompt which will be used for the LLM can provide the MIME type of media for the query.
          selector:
            text:
              multiline: true
          default: >-
            This argument is mandatory and must always be provided.

            Always specify the MIME type of the media.
            Choose a value that matches the file contents (for example image/jpeg, video/mp4, audio/mp3, text/plain, or application/pdf).
mode: parallel
max_exceeded: silent
variables:
  version: 20251019
fields:
  instructions:
    name: Instructions
    description: !input instructions_prompt
    selector:
      text:
        multiline: true
    required: true
  image_path:
    name: Image Path
    description: !input image_path_prompt
    selector:
      text:
    required: true
  mime_type:
    name: MIME Type
    description: !input mime_type_prompt
    selector:
      text:
    required: true
sequence:
  - variables:
      ai_task_entity: !input ai_task_entity
      instructions: "{{ instructions | default('') | trim }}"
      image_path: "{{ image_path | default('') | trim }}"
      mime_type: "{{ mime_type | default('') | trim }}"
  - if:
      - alias: Check if variables were set correctly
        condition: template
        value_template: "{{ not instructions }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: >-
              Unable to extract data because instructions is missing or incorrect.
      - alias: Stop the script
        stop: >-
          Unable to extract data because instructions is missing or incorrect.
        response_variable: response
  - if:
      - alias: Check if variables were set correctly
        condition: template
        value_template: "{{ (image_path | length == 0) or (not image_path.startswith('http://')) }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: >-
              Unable to extract data because image path is missing or invalid. Provide a valid HTTP URL for the camera image.
      - alias: Stop the script
        stop: >-
          Unable to extract data because image path is missing or invalid.
        response_variable: response
  - if:
      - alias: Check if variables were set correctly
        condition: template
        value_template: "{{ not mime_type.startswith(('image/', 'video/', 'audio/', 'text/', 'application/')) }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: >-
              Unable to extract data because MIME type is missing or incorrect.
      - alias: Stop the script
        stop: >-
          Unable to extract data because MIME type is missing or incorrect.
        response_variable: response
  - variables:
      attachments:
        media_content_id: "{{ image_path }}"
        media_content_type: "{{ mime_type }}"
  - if:
      - condition: template
        value_template: "{{ not ai_task_entity }}"
    then:
      - action: ai_task.generate_data
        data:
          task_name: Analyze content from a media or document file
          instructions: "{{ instructions }}"
          attachments: "{{ attachments }}"
        response_variable: result
    else:
      - action: ai_task.generate_data
        data:
          task_name: Analyze content from a media or document file
          instructions: "{{ instructions }}"
          attachments: "{{ attachments }}"
          entity_id: "{{ ai_task_entity }}"
        response_variable: result
  - variables:
      response:
        data: "{{ result.data }}"
  - stop: ""
    response_variable: response
