blueprint:
  name: Voice - File Content Analyzer
  author: DoThai
  description: >
    Phân tích hình ảnh từ camera và tự động lưu snapshot vào thư mục theo ngày trong /config/www/AnhAI/YYYY-MM-DD/
  domain: script
  homeassistant:
    min_version: 2025.8.0

  input:
    ai_task_entity:
      name: AI Task Entity
      description: "Entity của AI Task (ví dụ: ai_task.gemini_2_5_flash_ai_task)"
      selector:
        entity:
          filter:
            domain: ai_task

    instructions_prompt:
      name: Instructions
      description: "Yêu cầu AI cần thực hiện (mặc định: phát hiện người trong ảnh)"
      selector:
        text:
          multiline: true
      default: "Phân tích xem có người trong khung hình hay không"

fields:
  camera_entity:
    name: Camera Entity
    description: "Camera cần phân tích"
    selector:
      entity:
        filter:
          domain: camera
    required: true

  instructions:
    name: Instructions
    description: "Ghi đè yêu cầu nếu muốn"
    selector:
      text:
        multiline: true

mode: parallel
max_exceeded: silent

sequence:
  # 🧩 Tạo biến và đường dẫn
  - variables:
      ai_task_entity: !input ai_task_entity
      camera_entity: "{{ camera_entity }}"
      instructions: "{{ instructions or instructions_prompt }}"
      today: "{{ now().strftime('%Y-%m-%d') }}"
      folder_path: "/config/www/AnhAI/{{ today }}"
      filename: "snapshot_{{ camera_entity.split('.')[-1] }}.jpg"
      snapshot_file: "{{ folder_path }}/{{ filename }}"



  # 📸 Chụp ảnh camera lưu vào đúng thư mục theo ngày
  - service: camera.snapshot
    data:
      entity_id: "{{ camera_entity }}"
      filename: "{{ snapshot_file }}"

  # 🔗 Tạo đường dẫn media-source để AI đọc
  - variables:
      media_path: "local/AnhAI/{{ today }}/{{ filename }}"

  # 🤖 Gọi AI Task xử lý ảnh
  - service: ai_task.generate_data
    data:
      task_name: "Analyze camera snapshot"
      instructions: "{{ instructions }}"
      attachments:
        - media_content_id: "media-source://media_source/{{ media_path }}"
          media_content_type: "image/jpeg"
      entity_id: "{{ ai_task_entity }}"
    response_variable: result

  # 🧹 (Tuỳ chọn) – có thể thêm bước xoá file sau khi xử lý xong
  # - service: shell_command.delete_snapshot
  #   data:
  #     file: "{{ snapshot_file }}"

  - variables:
      response: "{{ result.data | default('Không có phản hồi từ AI.') }}"

  - stop: "{{ response }}"
