blueprint:
  name: Voice - File Content Analyzer
  author: thaidv
  description: >-
    # Tool designed to analyze and extract all types of information from media and document files

    ## Blueprint Setup

    ### Required

    * Google Generative AI integration must be installed and configured.

    ### Optional

    * Adjust the prompts for each field used in the script. The descriptions guide the LLM to provide the correct input.

    ### Note

    * Provide a concise and precise description for the script. This description will enable the LLM to recognize that the script is designed to extract data from a media or document file.

    * Make sure to expose the script to Assist after the script has been saved.

    * Do not alter the default script name.
  domain: script
  homeassistant:
    min_version: 2025.8.0
  input:
    google_ai_settings:
      name: Settings for Google Generative AI
      icon: mdi:google
      description: These settings allow you to set up the Google Generative AI integration.
      input:
        google_ai_entity:
          name: Google Generative AI Entity
          description: Select the Google Generative AI entity to use for analysis.
          selector:
            entity:
              domain: conversation
              integration: google_generative_ai
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        instructions_prompt:
          name: Instructions Prompt
          description: The prompt which will be used for the LLM can provide the request for the query.
          selector:
            text:
              multiline: true
          default: >-
            This argument is mandatory and must always be provided.

            The tool can analyze content and extract any type of information from an image, video, audio, or document, including text, numbers, objects, speech, and visual features.

            Always clearly specify exactly what data should be extracted.
        camera_selection_prompt:
          name: Camera Selection Prompt
          description: The prompt which will be used for the LLM to select the camera for analysis.
          selector:
            text:
              multiline: true
          default: >-
            This argument is mandatory and must always be provided.

            Select the camera you want to analyze from the following options:
            - kho: Camera Kho (entity: camera.ezvizkho)
            - cong: Camera Cổng (entity: camera.ezvizcong)  
            - san: Camera Sân (entity: camera.ezvizsan)
            - pkhach: Camera Phòng Khách (entity: camera.pkhach)

            Only enter the camera name (kho, cong, san, or pkhach).
mode: parallel
max_exceeded: silent
variables:
  version: 20251019
fields:
  google_ai_entity:
    name: Google AI Entity
    description: Select the Google Generative AI entity to use for image analysis.
    selector:
      entity:
        domain: conversation
        integration: google_generative_ai
    required: true
  instructions:
    name: Instructions
    description: !input instructions_prompt
    selector:
      text:
        multiline: true
    required: true
  camera_name:
    name: Camera Name
    description: !input camera_selection_prompt
    selector:
      select:
        options:
          - label: Camera Kho (camera.ezvizkho)
            value: kho
          - label: Camera Cổng (camera.ezvizcong)
            value: cong
          - label: Camera Sân (camera.ezvizsan)
            value: san
          - label: Camera Phòng Khách (camera.pkhach)
            value: pkhach
    required: true
sequence:
  - variables:
      google_ai_entity: "{{ google_ai_entity }}"
      instructions: "{{ instructions | default('') | trim }}"
      camera_name: "{{ camera_name | default('') | trim }}"
      
      # Lấy thông tin entity aliases từ sensor
      entity_aliases: "{{ state_attr('sensor.assist_entity_ids_and_aliases', 'entities') }}"
      
      # Map camera names to image URLs với entity IDs rõ ràng
      camera_url_map:
        kho: "http://localhost:1984/api/frame.jpeg?src=camera.ezvizkho"
        cong: "http://localhost:1984/api/frame.jpeg?src=camera.ezvizcong"
        san: "http://localhost:1984/api/frame.jpeg?src=camera.ezvizsan"
        pkhach: "http://localhost:1984/api/frame.jpeg?src=camera.pkhach"
      
      selected_camera_url: "{{ camera_url_map[camera_name] }}"
      
      # Tạo prompt với context về entities và aliases
      enhanced_prompt: >-
        Analyze this image from camera {{ camera_name }} (entity: {{ 
          'camera.ezvizkho' if camera_name == 'kho' else
          'camera.ezvizcong' if camera_name == 'cong' else
          'camera.ezvizsan' if camera_name == 'san' else
          'camera.pkhach'
        }}).
        
        {% if entity_aliases %}
        Available entities and aliases in the system: {{ entity_aliases }}
        {% endif %}
        
        Instructions: {{ instructions }}
      
  - if:
      - alias: Check if Google AI entity is selected
        condition: template
        value_template: "{{ not google_ai_entity }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: >-
              Google AI entity is required. Please select a Google Generative AI entity.
      - alias: Stop the script
        stop: >-
              Google AI entity is required. Please select a Google Generative AI entity.
        response_variable: response

  - if:
      - alias: Check if variables were set correctly
        condition: template
        value_template: "{{ not instructions }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: >-
              Unable to extract data because instructions is missing or incorrect.
      - alias: Stop the script
        stop: >-
          Unable to extract data because instructions is missing or incorrect.
        response_variable: response

  - if:
      - alias: Check if camera name is valid
        condition: template
        value_template: "{{ camera_name not in ['kho', 'cong', 'san', 'pkhach'] }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: >-
              Unable to extract data because camera selection is invalid. Please select kho, cong, san, or pkhach.
      - alias: Stop the script
        stop: >-
          Unable to extract data because camera selection is invalid.
        response_variable: response

  # Use Google Generative AI to analyze the image directly from URL
  - action: conversation.process
    data:
      agent_id: "{{ google_ai_entity }}"
      text: "{{ enhanced_prompt }}"
      attachment:
        url: "{{ selected_camera_url }}"
    response_variable: google_ai_result

  - if:
      - condition: template
        value_template: "{{ google_ai_result is not defined or google_ai_result.speech is not defined }}"
    then:
      - variables:
          response:
            error: "Failed to analyze image from camera {{ camera_name }}"
      - stop: "Failed to analyze camera image"
        response_variable: response

  - variables:
      response:
        data: "{{ google_ai_result.speech }}"
        camera_analyzed: "{{ camera_name }}"
        camera_entity: "{{
          'camera.ezvizkho' if camera_name == 'kho' else
          'camera.ezvizcong' if camera_name == 'cong' else
          'camera.ezvizsan' if camera_name == 'san' else
          'camera.pkhach'
        }}"
        analysis_success: true

  - stop: ""
    response_variable: response
