blueprint:
  name: Voice - Send Image to Telegram
  author: Thaidv
  description: >
    🖼️ Gửi ảnh tới Telegram dùng cho Voice Assistant  
    ✅ Đã sửa lỗi cú pháp YAML ("mapping values are not allowed here")  
    ✅ Đã sửa lỗi `expected int @ data['target']  
    ✅ Gửi đúng nhóm Telegram theo Chat ID nhập.
  domain: script
  homeassistant:
    min_version: 2024.10.0

  source_url: https://github.com/thaibacgiang/thaibot/blob/main/send_image_to_telegram.yaml

mode: queued
max: 30
max_exceeded: silent

input:
  chat_id:
    name: Chat ID
    description: "Nhập chat_id nhóm hoặc người nhận (VD: -1002936213456)"
    selector:
      text:
        multiline: false
        multiple: false

  caption:
    name: Caption
    description: "Mô tả/ghi chú cho ảnh (tùy chọn)"
    default: ""
    selector:
      text:
        multiline: true
        multiple: false

  image_path:
    name: Image Path
    description: >
      Đây là URL ảnh cần gửi.  
      Ví dụ:
        - http://localhost:1984/api/frame.jpeg?src=camera.ezvizkho  
        - http://localhost:1984/api/frame.jpeg?src=camera.ezvizcong
    selector:
      text:
        multiline: false
        multiple: false

  message:
    name: Message
    description: "Nội dung tin nhắn đi kèm (tuỳ chọn)"
    default: ""
    selector:
      text:
        multiline: true
        multiple: false

variables:
  version: 20251014

sequence:
  # Làm sạch dữ liệu đầu vào
  - variables:
      _chat_id: "{{ chat_id | int }}"
      _image_path: "{{ image_path | trim }}"
      _caption: "{{ caption | default('') | trim }}"
      _message: "{{ message | default('') | trim }}"
      _final_caption: "{{ _message if _message else _caption }}"

  # Gửi ảnh đến Telegram
  - action: telegram_bot.send_photo
    data:
      target: "{{ _chat_id }}"
      url: "{{ _image_path }}"
      caption: "{{ _final_caption }}"
    response_variable: telegram_result

  # Kiểm tra phản hồi Telegram
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ telegram_result is defined and telegram_result != false }}"
        sequence:
          - variables:
              response:
                status: success
                message: "✅ Gửi ảnh thành công!"
    default:
      - variables:
          response:
            status: failed
            message: "❌ Gửi ảnh thất bại!"

  - stop: ""
    response_variable: response
