blueprint:
  name: Voice - Send Image to Telegram
  author: Thaidv
  description: '# Tool for sending images to Telegram used for Voice Assistant'
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    telegram_settings:
      name: Settings for Telegram
      icon: mdi:telegram
      description: You can use these settings to configure Telegram for sending the image.
      input:
        chat_id:
          name: Chat ID
          description: The thread to send the image to.
          selector:
            text:
              multiline: false
              multiple: false
        caption:
          name: Caption
          description: The caption for the image (optional).
          selector:
            text:
              multiline: true
              multiple: false
          default: ''
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model).
      collapsed: true
      input:
        image_path_prompt:
          name: Image Path Prompt
          description: The prompt which will be used for the LLM to provide the image URL/path.
          selector:
            text:
              multiline: true
              multiple: false
          default: 'This argument is mandatory and must always be provided. Select the correct camera and provide the full URL for the image you want to send. Available cameras and their URLs: - Kho: http://localhost:1984/api/frame.jpeg?src=camera.ezvizkho - Cổng: http://localhost:1984/api/frame.jpeg?src=camera.ezvizcong - Sân: http://localhost:1984/api/frame.jpeg?src=camera.ezvizsan - Phòng Khách: http://localhost:1984/api/frame.jpeg?src=camera.pkhach Only enter the URL that matches the camera you want to send. Example: If you want to send an image from ''san'', enter http://localhost:1984/api/frame.jpeg?src=camera.ezvizsan'
        message_prompt:
          name: Message Prompt
          description: The prompt which will be used for the LLM to provide the message content.
          selector:
            text:
              multiline: true
              multiple: false
          default: 'This argument is optional. Enter the camera name (kho, cong, san, phong khach) to indicate which camera the image is from. You may also provide a short message to send along with the image. Example: "Image from Camera Sân" or "Camera Sân snapshot".'
  source_url: https://github.com/thaibacgiang/thaibot/blob/main/send_image_to_telegram.yaml
mode: queued
max: 30
max_exceeded: silent
variables:
  version: 20251009
fields:
  image_path:
    name: Image Path
    description: !input image_path_prompt
    selector:
      text:
    required: true
  message:
    name: Message
    description: !input message_prompt
    selector:
      text:
sequence:
- variables:
    image_path: '{{ image_path | default('''') | trim }}'
    message: '{{ message | default('''') | trim }}'
    final_caption: '{{ message if message else (caption | default('''')) }}'
    
# THAY THẾ telegram_bot.send_photo BẰNG pyscript.send_telegram_photo
- service: pyscript.send_telegram_photo
  data:
    chat_id: !input chat_id
    file_path: '{{ image_path }}'
    caption: '{{ final_caption }}'
  response_variable: pyscript_result

- choose:
  - conditions:
    - condition: template
      value_template: '{{ pyscript_result is defined and pyscript_result.success == true }}'
    sequence:
    - variables:
        response:
          data:
            status: success
            message: Gửi ảnh thành công
  default:
  - variables:
      response:
        error: '{{ pyscript_result.error | default("Gửi ảnh thất bại") }}'

- stop: ''
  response_variable: response
