blueprint:
  name: Voice - Send Image to Telegram
  author: Thaidv
  description: >
    # Tool for sending images to Telegram used for Voice Assistant  
    This version fixes the chat_id → target issue so it sends to the correct chat.
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    telegram_settings:
      name: Settings for Telegram
      icon: mdi:telegram
      description: Configure Telegram sending options.
      input:
        chat_id:
          name: Chat ID
          description: The thread or group ID to send the image to.
          selector:
            text:
              multiline: false
              multiple: false
        caption:
          name: Caption
          description: Optional text caption for the image.
          selector:
            text:
              multiline: true
              multiple: false
          default: ''
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: Finetune prompts for your specific model.
      collapsed: true
      input:
        image_path_prompt:
          name: Image Path Prompt
          default: >
            This argument is mandatory. Provide the full URL for the image to send.
        message_prompt:
          name: Message Prompt
          default: >
            Optional. Provide a short message or camera name.
  source_url: https://github.com/thaibacgiang/thaibot/blob/main/send_image_to_telegram.yaml
mode: queued
max: 30
max_exceeded: silent
variables:
  version: 20251009
fields:
  image_path:
    name: Image Path
    description: !input image_path_prompt
    selector:
      text:
    required: true
  message:
    name: Message
    description: !input message_prompt
    selector:
      text:
sequence:
  - variables:
      image_path: "{{ image_path | default('') | trim }}"
      message: "{{ message | default('') | trim }}"
      final_caption: "{{ message if message else (caption | default('')) }}"
  - action: telegram_bot.send_photo
    data:
      target: "{{ chat_id | int(default=0) if chat_id is string else chat_id }}"  # ✅ Sửa chat_id -> target
      url: "{{ image_path }}"
      caption: "{{ final_caption }}"
    response_variable: telegram_result
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ telegram_result is defined and telegram_result != false }}"
        sequence:
          - variables:
              response:
                data:
                  status: success
                  message: "✅ Gửi ảnh thành công!"
    default:
      - variables:
          response:
            error: "❌ Gửi ảnh thất bại!"
  - stop: ""
    response_variable: response
