blueprint:
  name: Voice - Send Image to Telegram
  author: Thaidv1
  description: >
    📸 Gửi ảnh từ Camera đến Telegram — phiên bản sửa lỗi hoàn toàn.
    - Hỗ trợ lọc URL Markdown.
    - Không còn lỗi LoggingUndefined.
    - Hiển thị caption rõ ràng và thân thiện.

  domain: script
  homeassistant:
    min_version: 2024.10.0

  input:
    telegram_settings:
      name: Cài đặt Telegram
      icon: mdi:telegram
      input:
        chat_id:
          name: Chat ID
          description: ID nhóm hoặc người nhận ảnh.
          selector:
            text:
              multiline: false
        caption:
          name: Caption mặc định
          description: Ghi chú đi kèm ảnh (nếu không có message riêng).
          selector:
            text:
              multiline: true
          default: ''

    prompt_settings:
      name: Cài đặt gợi ý cho AI
      icon: mdi:robot
      collapsed: true
      input:
        image_path_prompt:
          name: Gợi ý đường dẫn ảnh
          description: >
            Gợi ý giúp AI biết chọn URL camera nào. Nhập URL ảnh hợp lệ (http/https),
            ví dụ: http://192.168.1.23:1984/api/frame.jpeg?src=cam_cua_truoc
          selector:
            text:
              multiline: true
          default: >
            - Nhà xe: http://192.168.1.23:1984/api/frame.jpeg?src=cam_nha_xe
            - Cửa trước: http://192.168.1.23:1984/api/frame.jpeg?src=cam_cua_truoc
            - Phòng khách: http://192.168.1.23:1984/api/frame.jpeg?src=cam_phong_khach
        message_prompt:
          name: Gợi ý nội dung tin nhắn
          description: >
            Nhập tên camera hoặc mô tả ảnh. VD: "Ảnh từ Camera cửa trước"
          selector:
            text:
              multiline: true
          default: >
            "Ảnh từ Camera cửa trước" hoặc "Camera cam_cua_truoc snapshot"

  source_url: https://github.com/thaibacgiang/thaibot/blob/main/send_image_to_telegram.yaml

mode: queued
max: 30
max_exceeded: silent

variables:
  version: 20251024

fields:
  image_path:
    name: Image Path
    description: !input image_path_prompt
    selector:
      text:
    required: true

  message:
    name: Message
    description: !input message_prompt
    selector:
      text:

sequence:
  - variables:
      raw_path: "{{ image_path | default('') | trim }}"
      # Xóa định dạng Markdown kiểu [url](url)
      clean_path: >
        {% if '(' in raw_path and ')' in raw_path %}
          {{ raw_path | regex_replace('\\[.*?\\]\\((.*?)\\)', '\\1') }}
        {% else %}
          {{ raw_path }}
        {% endif %}
      final_caption: "{{ message if message|length > 0 else (caption | default('')) }}"

  - alias: "📤 Gửi ảnh đến Telegram"
    action: telegram_bot.send_photo
    data:
      chat_id: !input chat_id
      url: "{{ clean_path }}"
      caption: "{{ final_caption }}"
    response_variable: telegram_result

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ telegram_result is defined and telegram_result is not none }}"
        sequence:
          - variables:
              response:
                data:
                  status: "✅ Thành công"
                  message: "Ảnh đã được gửi đến Telegram"
    default:
      - variables:
          response:
            data:
              status: "❌ Thất bại"
              message: "Không thể gửi ảnh – kiểm tra lại URL hoặc kết nối Telegram"

  - stop: "{{ response }}"
