blueprint:
  name: Voice - Smart Camera Analyzer (Stable Base64 Snapshot)
  author: optimized_by_chatgpt
  description: >
    Phân tích hình ảnh từ camera bằng AI.
    - Tự nhận diện hỏi 1 camera hoặc tất cả camera.
    - Lưu ảnh tạm → chuyển base64 → gửi AI → luôn ổn định và nhanh.
  domain: script

  input:
    ai_task_entity:
      name: AI Task Entity
      selector:
        entity:
          filter:
            - domain: ai_task
      default:
    delay_between:
      name: Delay giữa các camera (khi hỏi nhiều)
      selector:
        number:
          min: 0
          max: 3
          step: 0.2
          unit_of_measurement: s
      default: 0.5

mode: parallel
max_exceeded: silent

fields:
  instructions:
    name: Câu hỏi về camera
    description: >
      Ví dụ:
      - Camera nhà xe có ai không?
      - Camera ban công đang thấy gì?
      - Kiểm tra tất cả camera xem có ai không.
    selector:
      text:
        multiline: true
    required: true

sequence:

  - variables:
      question: "{{ instructions | trim }}"
      ai_task_entity: !input ai_task_entity
      delay_between: !input delay_between

  - if:
      - condition: template
        value_template: "{{ not question }}"
    then:
      - stop: "Bạn chưa nhập câu hỏi."

  - variables:
      cams: >
        {% set cs = states.camera
        | selectattr('state','in',['idle','streaming','recording'])
        | map(attribute='entity_id') | list %}
        {{ cs }}
      q: "{{ question | lower }}"

  - variables:
      is_multi: >
        {{ 'tất cả' in q or 'toàn bộ' in q or 'all' in q }}
      cam_match: >
        {% for c in cams %}
        {% set name = (state_attr(c,'friendly_name')|default('')|lower) %}
        {% if q in name %}{{ c }}{% endif %}
        {% endfor %}
      final_camera: "{{ cam_match or '' }}"
      mode: >
        {% if is_multi %}multi
        {% elif final_camera %}single
        {% else %}multi
        {% endif %}

  # ===== SINGLE CAMERA =====
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ mode == 'single' }}"
        sequence:

          # Chụp ảnh
          - service: camera.snapshot
            data:
              entity_id: "{{ final_camera }}"
              filename: "/config/www/ai_snapshot.jpg"

          - variables:
              img_b64: "{{ '/config/www/ai_snapshot.jpg' | file | b64encode }}"
              cam_name: "{{ state_attr(final_camera,'friendly_name') or final_camera }}"
              prompt: >
                Trả lời tiếng Việt tự nhiên 1-3 câu.
                Câu hỏi: {{ question }}
                Camera: {{ cam_name }}

          # Gửi AI
          - action: ai_task.generate_data
            data:
              entity_id: "{{ ai_task_entity }}"
              instructions: "{{ prompt }}"
              attachments:
                - inline_data:
                    mime_type: image/jpeg
                    data: "{{ img_b64 }}"
            response_variable: result

          - variables:
              response:
                mode: single
                camera: "{{ cam_name }}"
                answer: "{{ result.data }}"
                timestamp: "{{ now().isoformat() }}"

          - stop: ""
            response_variable: response

  # ===== MULTI CAMERA =====
      - conditions:
          - condition: template
            value_template: "{{ mode == 'multi' }}"
        sequence:

          - variables:
              results: []

          - repeat:
              for_each: "{{ cams }}"
              sequence:

                # Chụp ảnh từng camera
                - service: camera.snapshot
                  data:
                    entity_id: "{{ repeat.item }}"
                    filename: "/config/www/ai_snapshot_{{ repeat.index }}.jpg"

                - variables:
                    img_b64: "{{ ('/config/www/ai_snapshot_' ~ repeat.index ~ '.jpg') | file | b64encode }}"
                    cam_name: "{{ state_attr(repeat.item,'friendly_name') or repeat.item }}"
                    prompt_each: >
                      Mô tả cảnh của camera {{ cam_name }} ngắn gọn.

                - action: ai_task.generate_data
                  data:
                    entity_id: "{{ ai_task_entity }}"
                    instructions: "{{ prompt_each }}"
                    attachments:
                      - inline_data:
                          mime_type: image/jpeg
                          data: "{{ img_b64 }}"
                  response_variable: res

                - variables:
                    results: "{{ results + [ cam_name ~ ': ' ~ (res.data | default('Không rõ')) ] }}"

                - delay:
                    seconds: "{{ delay_between }}"

          # Tổng hợp
          - action: ai_task.generate_data
            data:
              entity_id: "{{ ai_task_entity }}"
              instructions: >
                Tổng hợp mô tả các camera trong 2-4 câu tự nhiên:
                {{ results | join('\n') }}
            response_variable: summary

          - variables:
              response:
                mode: multi
                summary: "{{ summary.data }}"
                timestamp: "{{ now().isoformat() }}"

          - stop: ""
            response_variable: response
