blueprint:
  name: Voice - Smart Camera AI Analyzer (Auto)
  author: benbap
  description: 'Smart AI-powered camera analysis script (auto)

    - Không cần cấu hình danh sách camera thủ công

    - Tự lấy toàn bộ camera thật trong Home Assistant

    - Ưu tiên match friendly_name

    - Nếu không khớp thì match theo sensor aliases (giống blueprint Capture Camera
    Snapshot)

    - Nếu vẫn không khớp thì đoán theo từ khóa ("phòng khách", "ban công", "cửa")

    - Trả lời tiếng Việt, prompt tiếng Anh

    - Hỗ trợ structure (overview, cameras_with_people, cameras_no_people, cameras_error,
    summary)

    '
  domain: script
  homeassistant:
    min_version: 2025.8.0
  input:
    entity_aliases_settings:
      name: Settings for Entity Aliases
      icon: mdi:format-list-bulleted
      description: Sensor alias giống blueprint Capture Camera Snapshot
      input:
        entity_aliases:
          name: Entity Aliases
          selector:
            entity:
              filter:
              - domain:
                - sensor
                integration: template
              multiple: false
              reorder: false
    ai_task_settings:
      name: AI Task Settings
      icon: mdi:robot-outline
      collapsed: true
      input:
        ai_task_entity:
          name: AI Task Entity
          description: Leave empty to use system default AI Task
          selector:
            entity:
              filter:
              - domain:
                - ai_task
              multiple: false
              reorder: false
          default:
    prompt_settings:
      name: Prompt Settings
      icon: mdi:robot
      collapsed: true
      input:
        system_prompt:
          name: System Prompt (English)
          description: Main instructions for the LLM
          selector:
            text:
              multiline: true
              multiple: false
          default: "You are an AI assistant for a Home Assistant smart home system.
            You analyze live camera streams.\n\nIMPORTANT CONTEXT:\n- The user may
            ask you to:\n  * Detect people, pets, or motion\n  * Check if the camera
            is online/offline\n  * Describe what is seen in the image (objects, people,
            pets, background)\n- You are called from a script that may send you ONE
            or MULTIPLE cameras.\n- You MUST base your answer ONLY on the attached
            media.\n- You MUST answer IN VIETNAMESE with proper diacritics.\n\nUSER
            QUESTION:\n\"{user_question}\"\n\nAVAILABLE CAMERAS:\n{camera_list}\n\n###
            MODES\n1. DESCRIBE MODE (when user says “có những gì”, “thấy gì”, “bên
            trong có gì”)\n   - Describe EVERYTHING visible in the frame: people,
            pets (cat/dog), vehicles, objects, doors, background, lighting.\n   -
            Do NOT limit to people.\n   - Output should be short, clear, natural Vietnamese.\n2.
            DETECTION MODE (when user says “có người không”, “có mèo không”, “có ai
            không”)\n   - Focus on target the user asked (person/pet).\n   - If not
            seen → say clearly “Không thấy …”.\n   - Keep it short for TTS.\n3. MULTI-CAMERA
            MODE (when user says “camera nào”, “tất cả camera”, “kiểm tra tất cả”)\n
            \  - You will receive MULTIPLE camera attachments.\n   - You MUST return
            structured data:\n     * overview: short description of all cameras\n
            \    * cameras_with_people: cameras where you SEE people\n     * cameras_no_people:
            cameras where you see NO people\n     * cameras_error: cameras dark/blocked/offline\n
            \    * summary: ONE Vietnamese sentence ≤ 120 chars for TTS\nDETECTION
            RULES:\n- “Có người” = any visible human.\n- If user asked about pets,
            prioritize cats/dogs over people.\n- If the frame is too dark/blurred
            → say so, do not guess.\n- Do NOT describe fixed walls/furniture unless
            needed for location.\nOUTPUT RULES:\n- Always in Vietnamese.\n- If structure
            is provided, fill ALL required fields.\n- No Markdown, no code blocks.\n-
            Do NOT invent unseen cameras or content.\nSUMMARY FIELD:\n- One short
            Vietnamese sentence\n"
  source_url: https://raw.githubusercontent.com/TriTue2011/Blueprint/main/voice_camera_ai_analyzer.yaml
mode: parallel
max_exceeded: silent
variables:
  version: 20251031_auto_alias_nocamselect
fields:
  instructions:
    name: Camera Question
    description: Hỏi bất kỳ về camera
    selector:
      text:
        multiline: true
    required: true
sequence:
- variables:
    entity_aliases: !input entity_aliases
    ai_task_entity: !input ai_task_entity
    system_prompt: !input system_prompt
    user_question: '{{ instructions | default('''') | trim }}'
- if:
  - condition: template
    value_template: '{{ not user_question }}'
  then:
  - variables:
      response:
        error: Please provide a question about cameras.
  - stop: Missing question
    response_variable: response
- variables:
    all_cameras: '{% set cams = states.camera | map(attribute=''entity_id'') | list
      %} {{ cams }}

      '
    camera_list_text: "{% set ns = namespace(list=[]) %} {% for cam in all_cameras
      %}\n  {% set name = state_attr(cam, 'friendly_name') or cam %}\n  {% set ns.list
      = ns.list + ['- ' ~ name ~ ' (' ~ cam ~ ')'] %}\n{% endfor %} {{ ns.list | join('\\n')
      }}\n"
    user_question_lc: '{{ user_question | lower }}'
- variables:
    matched_camera_from_friendly: "{% set q = user_question | trim %} {% set found
      = '' %} {% for cam in all_cameras %}\n  {% set fn = (state_attr(cam, 'friendly_name')
      or '') | trim %}\n  {% if fn and (fn | lower) == (q | lower) %}\n    {% set
      found = cam %}\n  {% elif fn and (q | lower) in (fn | lower) %}\n    {% if not
      found %}\n      {% set found = cam %}\n    {% endif %}\n  {% endif %}\n{% endfor
      %} {{ found }}\n"
    matched_camera_from_alias: "{% set entities = state_attr(entity_aliases, 'entities')
      | default([]) %} {% set ql = user_question_lc %} {% set found = '' %} {% for
      item in entities %}\n  {% set eid = item.entity_id %}\n  {% set als = item.aliases
      | default([]) %}\n  {% if 'camera.' in eid %}\n    {% for a in als %}\n      {%
      if (a | lower) == ql or (ql in (a | lower)) %}\n        {% set found = eid %}\n
      \     {% endif %}\n    {% endfor %}\n  {% endif %}\n{% endfor %} {{ found }}\n"
    guessed_camera_hardcode: "{% if 'phòng khách' in user_question_lc %}\n  {% for
      cam in all_cameras %}\n    {% if 'phòng khách' in (state_attr(cam, 'friendly_name')
      | default('') | lower) %}\n      {{ cam }}\n    {% endif %}\n  {% endfor %}\n{%
      elif 'ban công' in user_question_lc %}\n  {% for cam in all_cameras %}\n    {%
      if 'ban công' in (state_attr(cam, 'friendly_name') | default('') | lower) %}\n
      \     {{ cam }}\n    {% endif %}\n  {% endfor %}\n{% elif 'cửa' in user_question_lc
      %}\n  {% for cam in all_cameras %}\n    {% if 'cửa' in (state_attr(cam, 'friendly_name')
      | default('') | lower) %}\n      {{ cam }}\n    {% endif %}\n  {% endfor %}\n{%
      else %}\n  {{ '' }}\n{% endif %}\n"
    fallback_camera: "{% if all_cameras | length > 0 %}\n  {{ all_cameras[0] }}\n{%
      else %}\n  {{ '' }}\n{% endif %}\n"
    final_single_camera: "{% if matched_camera_from_friendly %}\n  {{ matched_camera_from_friendly
      }}\n{% elif matched_camera_from_alias %}\n  {{ matched_camera_from_alias }}\n{%
      elif guessed_camera_hardcode %}\n  {{ guessed_camera_hardcode }}\n{% else %}\n
      \ {{ fallback_camera }}\n{% endif %}\n"
    use_single_camera: "{% set q = user_question_lc %} {% if 'tất cả' in q\n      or
      'all camera' in q\n      or 'camera nào' in q\n      or 'những camera' in q\n
      \     or 'các camera' in q\n      or 'which cameras' in q\n      or 'check all'
      in q %}\n  false\n{% else %}\n  true\n{% endif %}\n"
- variables:
    single_attachment: "{\n  \"media_content_id\": \"media-source://camera/{{ final_single_camera
      }}\",\n  \"media_content_type\": \"application/vnd.apple.mpegurl\",\n  \"metadata\":
      {\n    \"title\": \"{{ state_attr(final_single_camera, 'friendly_name') or final_single_camera
      }}\",\n    \"thumbnail\": \"/api/camera_proxy/{{ final_single_camera }}\",\n
      \   \"media_class\": \"video\"\n  }\n}\n"
    all_attachments: "{% set ns = namespace(items=[]) %} {% for cam in all_cameras
      %}\n  {% if states(cam) is not none %}\n    {% set name = state_attr(cam, 'friendly_name')
      or cam %}\n    {% set item = {\n      'media_content_id': 'media-source://camera/'
      ~ cam,\n      'media_content_type': 'application/vnd.apple.mpegurl',\n      'metadata':
      {\n        'title': name,\n        'thumbnail': '/api/camera_proxy/' ~ cam,\n
      \       'media_class': 'video'\n      }\n    } %}\n    {% set ns.items = ns.items
      + [item] %}\n  {% endif %}\n{% endfor %} {{ ns.items }}\n"
    camera_count: '{{ all_cameras | length }}'
- variables:
    final_prompt: "{{ system_prompt\n   | replace('{camera_list}', camera_list_text)\n
      \  | replace('{user_question}', user_question) }}\n"
- choose:
  - conditions:
    - condition: template
      value_template: '{{ not ai_task_entity }}'
    sequence:
    - action: ai_task.generate_data
      data:
        task_name: Smart Camera Analysis
        instructions: '{{ final_prompt }}'
        attachments: "{% if use_single_camera %}\n  {{ [single_attachment] }}\n{%
          else %}\n  {{ all_attachments }}\n{% endif %}\n"
        structure:
          overview:
            description: Short status of all cameras
            required: true
            selector:
              text: {}
          cameras_with_people:
            description: List of cameras with people
            required: true
            selector:
              text: {}
          cameras_no_people:
            description: List of cameras without people
            required: true
            selector:
              text: {}
          cameras_error:
            description: List of cameras with errors
            required: true
            selector:
              text: {}
          summary:
            description: One sentence summary in Vietnamese
            required: true
            selector:
              text: {}
      response_variable: ai_result
  - conditions:
    - condition: template
      value_template: '{{ ai_task_entity is not none }}'
    sequence:
    - action: ai_task.generate_data
      data:
        entity_id: '{{ ai_task_entity }}'
        task_name: Smart Camera Analysis
        instructions: '{{ final_prompt }}'
        attachments: "{% if use_single_camera %}\n  {{ [single_attachment] }}\n{%
          else %}\n  {{ all_attachments }}\n{% endif %}\n"
        structure:
          overview:
            description: Short status of all cameras
            required: true
            selector:
              text: {}
          cameras_with_people:
            description: List of cameras with people
            required: true
            selector:
              text: {}
          cameras_no_people:
            description: List of cameras without people
            required: true
            selector:
              text: {}
          cameras_error:
            description: List of cameras with errors
            required: true
            selector:
              text: {}
          summary:
            description: One sentence summary in Vietnamese
            required: true
            selector:
              text: {}
      response_variable: ai_result
- variables:
    response:
      mode: '{{ ''single'' if use_single_camera else ''multi'' }}'
      camera_count: '{{ camera_count }}'
      selected_camera: '{{ final_single_camera }}'
      matched_camera_from_friendly: '{{ matched_camera_from_friendly }}'
      matched_camera_from_alias: '{{ matched_camera_from_alias }}'
      guessed_camera_hardcode: '{{ guessed_camera_hardcode }}'
      data: '{{ ai_result.data }}'
- stop: ''
  response_variable: response

