blueprint:
  name: Voice - Capture Camera Snapshot
  author: luuquanhddd
  description: >-
    # Tool for capturing camera snapshots used for Voice Assistant

    ## Blueprint Setup

    ### Required

    * A template sensor stores all information about entity aliases needs to be configured in `config/configuration.yaml`; The sensor is required for friendly-name lookup.

    ```
    #File configuration.yaml
    shell_command:
      get_entity_alias: jq '[.data.entities[] | select(.options.conversation.should_expose == true and (.aliases | length > 0)) | {entity_id, aliases}]' ./.storage/core.entity_registry
    template:
      - triggers:
          - trigger: homeassistant
            event: start
          - trigger: event
            event_type: event_template_reloaded
        actions:
          - action: shell_command.get_entity_alias
            response_variable: response
        sensor:
          - name: "Assist: Entity IDs and Aliases"
            unique_id: entity_ids_and_aliases
            icon: mdi:format-list-bulleted
            device_class: timestamp
            state: "{{ now().isoformat() }}"
            attributes:
              entities: "{{ response.stdout }}"
    ```

    * Ensure the directory defined in the snapshot settings exists (default is `/media`).

    ### Optional

    * Adjust the prompts for each field used in the script. The descriptions guide the LLM to provide the correct input.

    ### Note

    * Provide a concise and precise description for the script. This will be utilized by the LLM to understand it should use this script for capturing a snapshot from a camera.

    * Make sure to expose camera entities to Assist.

    * Make sure to expose the script to Assist after the script has been saved.

    * Do not alter the default script name.
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    entity_aliases_settings:
      name: Settings for Entity Aliases
      icon: mdi:format-list-bulleted
      description: You can use these settings to configure a template sensor that stores all information about entity aliases.
      input:
        entity_aliases:
          name: Entity Aliases
          selector:
            entity:
              filter:
                - domain: sensor
                  integration: template
    snapshot_settings:
      name: Settings for Snapshot Output
      icon: mdi:folder-image
      description: Configure where snapshots should be stored and how filenames are generated.
      collapsed: true
      input:
        snapshot_directory:
          name: Snapshot Directory
          description: Absolute path where the snapshot will be stored (default is `/media`).
          selector:
            text:
          default: /media
        snapshot_filename_prefix:
          name: Snapshot Filename Prefix
          description: Prefix used when generating the snapshot filename.
          selector:
            text:
          default: camera_snapshot_
        snapshot_file_extension:
          name: Snapshot File Extension
          description: File extension to use for the snapshot (for example jpg or png).
          selector:
            text:
          default: jpg
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        camera_name_prompt:
          name: Camera Name Prompt
          description: The prompt which will be used for the LLM can provide the camera name.
          selector:
            text:
              multiline: true
          default: >-
            This argument is mandatory and must always be provided.

            Specify the camera name to capture the snapshot from.

            Use the friendly name that appears in Home Assistant (for example "Cam cửa trước").
mode: parallel
max_exceeded: silent
variables:
  version: 20251019
fields:
  camera_name:
    name: Camera Name
    description: !input camera_name_prompt
    selector:
      text:
    required: true
sequence:
  - variables:
      entity_aliases: !input entity_aliases
      camera_name: "{{ camera_name | default('') | trim }}"
      snapshot_directory_input: !input snapshot_directory
      snapshot_directory: "{{ snapshot_directory_input | default('/media', true) | trim }}"
      snapshot_prefix_input: !input snapshot_filename_prefix
      snapshot_prefix: "{{ snapshot_prefix_input | default('camera_snapshot_', true) | trim }}"
      snapshot_extension_input: !input snapshot_file_extension
      snapshot_extension: "{{ snapshot_extension_input | default('jpg', true) | trim | lower }}"
  
  # Debug: Log thông tin đầu vào
  - service: system_log.write
    data:
      level: info
      message: >-
        Voice command received: 
        Camera name: '{{ camera_name }}'
        All cameras: {{ states.camera | map(attribute='attributes.friendly_name') | list }}
  
  - alias: Validate camera name with better matching
    variables:
      friendly_match: "{{ states.camera | selectattr('attributes.friendly_name', '==', camera_name) | list }}"
      # Tìm kiếm không phân biệt hoa thường và tìm theo từ khóa
      keyword_match: >-
        {% set matches = [] %}
        {% for camera in states.camera %}
          {% set friendly_name = camera.attributes.friendly_name | default('') | lower %}
          {% set search_name = camera_name | lower %}
          {% if search_name in friendly_name or friendly_name in search_name %}
            {% set matches = matches + [camera] %}
          {% endif %}
        {% endfor %}
        {{ matches }}
      alias_match: "{{ state_attr(entity_aliases, 'entities') | default([]) | selectattr('entity_id', 'match', 'camera\\.') | selectattr('aliases', 'contains', camera_name) | list }}"
    
    # Debug kết quả tìm kiếm
  - service: system_log.write
    data:
      level: info
      message: >-
        Camera search results: 
        Friendly match: {{ friendly_match | length }}
        Keyword match: {{ keyword_match | length }}
        Alias match: {{ alias_match | length }}
        Keyword matches: {{ keyword_match | map(attribute='attributes.friendly_name') | list }}
  
  - alias: Check if camera found
    if:
      - condition: template
        value_template: >-
          {{ not camera_name or (friendly_match | length == 0 and keyword_match | length == 0 and alias_match | length == 0) }}
    then:
      - service: system_log.write
        data:
          level: error
          message: >-
            Camera not found: '{{ camera_name }}'. 
            Available cameras: {{ states.camera | map(attribute='attributes.friendly_name') | list }}
      - variables:
          response:
            error: "Không tìm thấy camera '{{ camera_name }}'. Các camera có sẵn: {{ states.camera | map(attribute='attributes.friendly_name') | list | join(', ') }}"
      - stop: "Camera không hợp lệ"
        response_variable: response

  - alias: Validate snapshot settings
    if:
      - condition: template
        value_template: >-
          {{ not snapshot_directory }}
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: Unable to capture a snapshot because the snapshot directory is missing.
      - alias: Stop the script
        stop: Unable to capture a snapshot because the snapshot directory is missing.
        response_variable: response

  - variables:
      camera_entity_id: >-
        {% if friendly_match | length > 0 %}
          {{ friendly_match[0].entity_id }}
        {% elif keyword_match | length > 0 %}
          {{ keyword_match[0].entity_id }}
        {% elif alias_match | length > 0 %}
          {{ alias_match[0].entity_id }}
        {% endif %}
      
      # Tạo đường dẫn theo ngày
      today_folder: "{{ now().strftime('%Y-%m-%d') }}"
      snapshot_directory_with_date: "{{ snapshot_directory.rstrip('/\\') }}/{{ today_folder }}"
      sanitized_prefix: >-
        {% if snapshot_prefix %}
          {{ snapshot_prefix | regex_replace('[^0-9A-Za-z_-]', '_') }}
        {% else %}
          camera_snapshot_
        {% endif %}
      sanitized_extension: >-
        {% if snapshot_extension %}
          {% set ext = snapshot_extension | regex_replace('[^0-9a-z]', '') %}
          {{ '.' ~ (ext if ext else 'jpg') }}
        {% else %}
          .jpg
        {% endif %}
      snapshot_random_suffix: "{{ '%05d' | format(range(0, 100000) | random) }}"
      snapshot_filename: >-
        {{ sanitized_prefix ~ now().strftime('%Y%m%d_%H%M%S') ~ '_' ~ snapshot_random_suffix ~ sanitized_extension }}
      snapshot_full_path: >-
        {{ snapshot_directory_with_date ~ '/' ~ snapshot_filename }}
      returned_image_path: >-
        {% set prefix = '/media/' %}
        {% if snapshot_full_path.startswith(prefix) %}
          {{ 'local/' ~ snapshot_full_path[prefix | length:] }}
        {% else %}
          {{ snapshot_full_path }}
        {% endif %}
  
  # Tạo thư mục nếu chưa tồn tại
  - alias: Create directory if not exists
    service: shell_command.create_directory
    data:
      path: "{{ snapshot_directory_with_date }}"
  
  # Debug thông tin cuối cùng
  - service: system_log.write
    data:
      level: info
      message: >-
        Final execution: 
        Camera entity: {{ camera_entity_id }}
        Full path: {{ snapshot_full_path }}
        Date folder: {{ today_folder }}

  - action: camera.snapshot
    target:
      entity_id: "{{ camera_entity_id }}"
    data:
      filename: "{{ snapshot_full_path }}"
  
  - variables:
      response:
        success: true
        image_path: "{{ returned_image_path }}"
        camera: "{{ camera_entity_id }}"
        message: "Đã chụp ảnh từ camera {{ camera_name }} thành công"
  
  - stop: "Snapshot captured successfully"
    response_variable: response
