blueprint:
  name: Voice - Smart Camera Analyzer (Single + Sequential)
  author: Thaidv_fixed + optimized_by_chatgpt
  description: >
    Trả lời câu hỏi về camera:
    - Nếu hỏi 1 camera → Phân tích trực tiếp
    - Nếu hỏi nhiều camera → Phân tích từng camera rồi tổng hợp
    Đã tối ưu tốc độ bằng snapshot Go2RTC (1-3 giây phản hồi).
  domain: script
  homeassistant:
    min_version: 2025.8.0

  input:
    entity_aliases_settings:
      name: Entity Aliases Sensor
      icon: mdi:format-list-bulleted
      input:
        entity_aliases:
          name: Entity Aliases Sensor
          selector:
            entity:
              filter:
                - domain: sensor
                  integration: template
          default:

    ai_task_settings:
      name: AI Task Settings
      icon: mdi:robot-outline
      collapsed: true
      input:
        ai_task_entity:
          name: AI Task Entity (nếu bỏ trống sẽ dùng mặc định hệ thống)
          selector:
            entity:
              filter:
                - domain: ai_task
          default:
        delay_between_cameras:
          name: Delay Between Cameras (khi phân tích nhiều camera)
          selector:
            number:
              min: 0
              max: 3
              step: 0.2
              unit_of_measurement: s
          default: 0.5

mode: parallel
max_exceeded: silent

fields:
  instructions:
    name: Camera Question
    description: >
      Ví dụ:
      - Camera nhà xe có người không?
      - Camera phòng khách đang thấy gì?
      - Kiểm tra tất cả camera xem có ai không.
    selector:
      text:
        multiline: true
    required: true

sequence:
  - variables:
      entity_aliases: !input entity_aliases
      ai_task_entity: !input ai_task_entity
      delay_between_cameras: !input delay_between_cameras
      user_question: "{{ instructions | trim }}"

  - if:
      - condition: template
        value_template: "{{ not user_question }}"
    then:
      - stop: "Vui lòng nói câu hỏi cho camera."

  - variables:
      all_cameras: >
        {% set cams = states.camera
        | selectattr('state', 'in', ['idle','streaming','recording'])
        | map(attribute='entity_id') | list %}
        {{ cams }}

      user_question_lc: "{{ user_question | lower }}"

  - variables:
      is_multi_camera_request: >
        {% set q=user_question_lc %}
        {{ 'tất cả' in q or 'toàn bộ' in q or 'all camera' in q or 'check all' in q }}

      matched_camera_from_friendly: >
        {% set q=user_question_lc %}
        {% for cam in all_cameras %}
        {% set fn=(state_attr(cam,'friendly_name')|default('')|lower) %}
        {% if q in fn %}{{ cam }}{% endif %}
        {% endfor %}

      matched_camera_from_alias: >
        {% set q=user_question_lc %}
        {% set ents = state_attr(entity_aliases,'entities')|default([]) %}
        {% for item in ents %}
          {% if 'camera.' in item.entity_id %}
            {% for a in item.aliases|default([]) %}
              {% if q in (a|lower) %}
                {{ item.entity_id }}
              {% endif %}
            {% endfor %}
          {% endif %}
        {% endfor %}

      final_camera: >
        {{ matched_camera_from_friendly or matched_camera_from_alias or '' }}

      use_mode: >
        {% if is_multi_camera_request %}multi
        {% elif final_camera %}single
        {% else %}multi
        {% endif %}

  # ==== SINGLE CAMERA ====
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ use_mode == 'single' }}"
        sequence:
          - variables:
              camera_name: "{{ state_attr(final_camera, 'friendly_name') or final_camera }}"
              camera_attachment:
                media_content_id: >-
                  http://192.168.1.23:1984/api/frame.jpeg?src={{ final_camera | replace('camera.','') }}
                media_content_type: image/jpeg
              single_prompt: >
                Trả lời tiếng Việt tự nhiên 1-3 câu. Nếu tối hoặc không rõ, hãy nói "Camera bị tối hoặc che khuất".
                Câu hỏi: {{ user_question }}
                Camera: {{ camera_name }}

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not ai_task_entity }}"
                sequence:
                  - action: ai_task.generate_data
                    data:
                      instructions: "{{ single_prompt }}"
                      attachments:
                        - "{{ camera_attachment }}"
                    response_variable: ai_result
            default:
              - action: ai_task.generate_data
                data:
                  entity_id: "{{ ai_task_entity }}"
                  instructions: "{{ single_prompt }}"
                  attachments:
                    - "{{ camera_attachment }}"
                response_variable: ai_result

          - variables:
              response:
                mode: single
                answer: "{{ ai_result.data }}"
                camera: "{{ camera_name }}"
                timestamp: "{{ now().isoformat() }}"

          - stop: ""
            response_variable: response

  # ==== MULTI CAMERA ====
      - conditions:
          - condition: template
            value_template: "{{ use_mode == 'multi' }}"
        sequence:
          - variables:
              camera_results: []

          - repeat:
              for_each: "{{ all_cameras }}"
              sequence:
                - variables:
                    current_camera: "{{ repeat.item }}"
                    camera_name: "{{ state_attr(repeat.item,'friendly_name') or repeat.item }}"
                    camera_attachment:
                      media_content_id: >-
                        http://192.168.1.23:1984/api/frame.jpeg?src={{ current_camera | replace('camera.','') }}
                      media_content_type: image/jpeg

                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ not ai_task_entity }}"
                      sequence:
                        - action: ai_task.generate_data
                          data:
                            instructions: "Mô tả hình ảnh camera {{ camera_name }}:"
                            attachments:
                              - "{{ camera_attachment }}"
                          response_variable: ai_single
                    default:
                      - action: ai_task.generate_data
                        data:
                          entity_id: "{{ ai_task_entity }}"
                          instructions: "Mô tả hình ảnh camera {{ camera_name }}:"
                          attachments:
                            - "{{ camera_attachment }}"
                        response_variable: ai_single

                - variables:
                    camera_results: >
                      {{ camera_results + [ camera_name ~ ": " ~ (ai_single.data | default("Không phân tích được")) ] }}

                - delay:
                    seconds: "{{ delay_between_cameras }}"

          - action: ai_task.generate_data
            data:
              entity_id: "{{ ai_task_entity }}"
              instructions: >
                Tổng hợp các mô tả sau thành 2-4 câu tiếng Việt tự nhiên:
                {{ camera_results | join("\n") }}
            response_variable: summary

          - variables:
              response:
                mode: multi
                summary: "{{ summary.data }}"
                timestamp: "{{ now().isoformat() }}"

          - stop: ""
            response_variable: response
