blueprint:
  name: Voice - Smart Camera AI Analyzer
  author: Thai
  description: 'Smart AI-powered camera analysis script (auto)

    - Không cần cấu hình danh sách camera thủ công
    - Tự lấy toàn bộ camera thật trong Home Assistant
    - Ưu tiên match friendly_name
    - Nếu không khớp thì match theo sensor aliases (giống blueprint Capture Camera
    Snapshot)
    - Nếu vẫn không khớp thì đoán theo từ khóa với độ ưu tiên cao hơn
    - Trả lời tiếng Việt, prompt tiếng Anh
    - Hỗ trợ structure (overview, cameras_with_people, cameras_no_people, cameras_error,
    summary)
    '
  domain: script
  homeassistant:
    min_version: 2025.8.0
  input:
    entity_aliases_settings:
      name: Settings for Entity Aliases
      icon: mdi:format-list-bulleted
      description: Sensor alias giống blueprint Capture Camera Snapshot
      input:
        entity_aliases:
          name: Entity Aliases
          selector:
            entity:
              filter:
              - domain:
                - sensor
                integration: template
              multiple: false
              reorder: false
    ai_task_settings:
      name: AI Task Settings
      icon: mdi:robot-outline
      collapsed: true
      input:
        ai_task_entity:
          name: AI Task Entity
          description: Leave empty to use system default AI Task
          selector:
            entity:
              filter:
              - domain:
                - ai_task
              multiple: false
              reorder: false
          default:
    prompt_settings:
      name: Prompt Settings
      icon: mdi:robot
      collapsed: true
      input:
        system_prompt:
          name: System Prompt (English)
          description: Main instructions for the LLM
          selector:
            text:
              multiline: true
              multiple: false
          default: "You are an AI assistant for a Home Assistant smart home system.
            You analyze live camera streams.\n\nIMPORTANT CONTEXT:\n- The user may
            ask you to:\n  * Detect people, pets, or motion\n  * Check if the camera
            is online/offline\n  * Describe what is seen in the image (objects, people,
            pets, background)\n- You are called from a script that may send you ONE
            or MULTIPLE cameras.\n- You MUST base your answer ONLY on the attached
            media.\n- You MUST answer IN VIETNAMESE with proper diacritics.\n\nUSER
            QUESTION:\n\"{user_question}\"\n\nAVAILABLE CAMERAS:\n{camera_list}\n\n###
            MODES\n1. DESCRIBE MODE (when user says \"có những gì\", \"thấy gì\", \"bên
            trong có gì\")\n   - Describe EVERYTHING visible in the frame: people,
            pets (cat/dog), vehicles, objects, doors, background, lighting.\n   -
            Do NOT limit to people.\n   - Output should be short, clear, natural Vietnamese.\n2.
            DETECTION MODE (when user says \"có người không\", \"có mèo không\", \"có ai
            không\")\n   - Focus on target the user asked (person/pet).\n   - If not
            seen → say clearly \"Không thấy …\".\n   - Keep it short for TTS.\n3. MULTI-CAMERA
            MODE (when user says \"camera nào\", \"tất cả camera\", \"kiểm tra tất cả\")\n
            \  - You will receive MULTIPLE camera attachments.\n   - You MUST return
            structured data:\n     * overview: short description of all cameras\n
            \    * cameras_with_people: cameras where you SEE people\n     * cameras_no_people:
            cameras where you see NO people\n     * cameras_error: cameras dark/blocked/offline\n
            \    * summary: ONE Vietnamese sentence ≤ 120 chars for TTS\nDETECTION
            RULES:\n- \"Có người\" = any visible human.\n- If user asked about pets,
            prioritize cats/dogs over people.\n- If the frame is too dark/blurred
            → say so, do not guess.\n- Do NOT describe fixed walls/furniture unless
            needed for location.\nOUTPUT RULES:\n- Always in Vietnamese.\n- If structure
            is provided, fill ALL required fields.\n- No Markdown, no code blocks.\n-
            Do NOT invent unseen cameras or content.\nSUMMARY FIELD:\n- One short
            Vietnamese sentence\n"
  source_url: https://github.com/thaibacgiang/thaibot/blob/main/Voice_Smart_Camera_AI_Analyzer.yaml
mode: parallel
max_exceeded: silent
variables:
  version: 20251031_improved_camera_matching
fields:
  instructions:
    name: Camera Question
    description: Hỏi bất kỳ về camera
    selector:
      text:
        multiline: true
    required: true
sequence:
- variables:
    entity_aliases: !input entity_aliases
    ai_task_entity: !input ai_task_entity
    system_prompt: !input system_prompt
    user_question: '{{ instructions | default('''') | trim }}'
- if:
  - condition: template
    value_template: '{{ not user_question }}'
  then:
  - variables:
      response:
        error: Please provide a question about cameras.
  - stop: Missing question
    response_variable: response
- variables:
    all_cameras: '{{ states.camera | map(attribute=''entity_id'') | list }}'
    camera_list_text: "{% set ns = namespace(list=[]) %} {% for cam in all_cameras %}\n  {% set name = state_attr(cam, 'friendly_name') or cam %}\n  {% set ns.list = ns.list + ['- ' ~ name ~ ' (' ~ cam ~ ')'] %}\n{% endfor %} {{ ns.list | join('\\n') }}\n"
    user_question_lc: '{{ user_question | lower }}'
- variables:
    # Tìm kiếm chính xác hơn - ưu tiên từ khóa cụ thể
    matched_camera_from_friendly: >-
      {% set q = user_question | trim %}
      {% set ql = user_question_lc %}
      {% set found = '' %}
      {% set exact_matches = [] %}
      {% set partial_matches = [] %}
      
      {% for cam in all_cameras %}
        {% set fn = (state_attr(cam, 'friendly_name') or '') | trim %}
        {% set fnl = fn | lower %}
        
        {# Ưu tiên 1: Tên chính xác hoàn toàn #}
        {% if fn and fnl == ql %}
          {% set exact_matches = exact_matches + [cam] %}
        {# Ưu tiên 2: Từ khóa chính xác trong tên #}
        {% elif 'phòng master' in ql and 'phòng master' in fnl %}
          {% set exact_matches = exact_matches + [cam] %}
        {% elif 'phòng ngủ master' in ql and 'phòng ngủ master' in fnl %}
          {% set exact_matches = exact_matches + [cam] %}
        {% elif 'nhà xe' in ql and 'nhà xe' in fnl %}
          {% set exact_matches = exact_matches + [cam] %}
        {% elif 'phòng khách' in ql and 'phòng khách' in fnl %}
          {% set exact_matches = exact_matches + [cam] %}
        {% elif 'ban công' in ql and 'ban công' in fnl %}
          {% set exact_matches = exact_matches + [cam] %}
        {% elif 'cửa trước' in ql and 'cửa trước' in fnl %}
          {% set exact_matches = exact_matches + [cam] %}
        {% elif 'cửa sau' in ql and 'cửa sau' in fnl %}
          {% set exact_matches = exact_matches + [cam] %}
        {# Ưu tiên 3: Từ khóa chứa trong tên #}
        {% elif fn and ql in fnl %}
          {% set partial_matches = partial_matches + [cam] %}
        {% endif %}
      {% endfor %}
      
      {% if exact_matches | length > 0 %}
        {{ exact_matches[0] }}
      {% elif partial_matches | length > 0 %}
        {{ partial_matches[0] }}
      {% else %}
        {{ '' }}
      {% endif %}

    matched_camera_from_alias: >-
      {% set entities = state_attr(entity_aliases, 'entities') | default([]) %}
      {% set ql = user_question_lc %}
      {% set found = '' %}
      {% set exact_alias_matches = [] %}
      {% set partial_alias_matches = [] %}
      
      {% for item in entities %}
        {% set eid = item.entity_id %}
        {% set als = item.aliases | default([]) %}
        {% if 'camera.' in eid %}
          {% for a in als %}
            {% set al = a | lower %}
            {% if al == ql %}
              {% set exact_alias_matches = exact_alias_matches + [eid] %}
            {% elif ql in al %}
              {% set partial_alias_matches = partial_alias_matches + [eid] %}
            {% endif %}
          {% endfor %}
        {% endif %}
      {% endfor %}
      
      {% if exact_alias_matches | length > 0 %}
        {{ exact_alias_matches[0] }}
      {% elif partial_alias_matches | length > 0 %}
        {{ partial_alias_matches[0] }}
      {% else %}
        {{ '' }}
      {% endif %}

    # Tìm kiếm thông minh hơn với từ khóa cụ thể
    guessed_camera_smart: >-
      {% set ql = user_question_lc %}
      {% set found = '' %}
      {% set priority_matches = [] %}
      {% set normal_matches = [] %}
      
      {# Từ khóa ưu tiên cao - phải khớp chính xác #}
      {% if 'phòng master' in ql or 'phòng ngủ master' in ql %}
        {% for cam in all_cameras %}
          {% set fn = (state_attr(cam, 'friendly_name') | default('')) | lower %}
          {% if 'master' in fn or 'phòng master' in fn or 'phòng ngủ master' in fn %}
            {% set priority_matches = priority_matches + [cam] %}
          {% endif %}
        {% endfor %}
      
      {% elif 'nhà xe' in ql %}
        {% for cam in all_cameras %}
          {% set fn = (state_attr(cam, 'friendly_name') | default('')) | lower %}
          {% if 'nhà xe' in fn or 'garage' in fn %}
            {% set priority_matches = priority_matches + [cam] %}
          {% endif %}
        {% endfor %}
      
      {% elif 'phòng khách' in ql %}
        {% for cam in all_cameras %}
          {% set fn = (state_attr(cam, 'friendly_name') | default('')) | lower %}
          {% if 'phòng khách' in fn or 'living room' in fn %}
            {% set priority_matches = priority_matches + [cam] %}
          {% endif %}
        {% endfor %}
      
      {% elif 'ban công' in ql %}
        {% for cam in all_cameras %}
          {% set fn = (state_attr(cam, 'friendly_name') | default('')) | lower %}
          {% if 'ban công' in fn or 'balcony' in fn %}
            {% set priority_matches = priority_matches + [cam] %}
          {% endif %}
        {% endfor %}
      
      {% elif 'cửa trước' in ql %}
        {% for cam in all_cameras %}
          {% set fn = (state_attr(cam, 'friendly_name') | default('')) | lower %}
          {% if 'cửa trước' in fn or 'front door' in fn %}
            {% set priority_matches = priority_matches + [cam] %}
          {% endif %}
        {% endfor %}
      
      {% elif 'cửa sau' in ql %}
        {% for cam in all_cameras %}
          {% set fn = (state_attr(cam, 'friendly_name') | default('')) | lower %}
          {% if 'cửa sau' in fn or 'back door' in fn %}
            {% set priority_matches = priority_matches + [cam] %}
          {% endif %}
        {% endfor %}
      
      {# Tìm kiếm chung #}
      {% else %}
        {% for cam in all_cameras %}
          {% set fn = (state_attr(cam, 'friendly_name') | default('')) | lower %}
          {% if ql in fn %}
            {% set normal_matches = normal_matches + [cam] %}
          {% endif %}
        {% endfor %}
      {% endif %}
      
      {% if priority_matches | length > 0 %}
        {{ priority_matches[0] }}
      {% elif normal_matches | length > 0 %}
        {{ normal_matches[0] }}
      {% else %}
        {{ '' }}
      {% endif %}

    fallback_camera: >-
      {% if all_cameras | length > 0 %}
        {{ all_cameras[0] }}
      {% else %}
        {{ '' }}
      {% endif %}

    final_single_camera: >-
      {% if matched_camera_from_friendly %}
        {{ matched_camera_from_friendly }}
      {% elif matched_camera_from_alias %}
        {{ matched_camera_from_alias }}
      {% elif guessed_camera_smart %}
        {{ guessed_camera_smart }}
      {% else %}
        {{ fallback_camera }}
      {% endif %}

    use_single_camera: >-
      {% set q = user_question_lc %}
      {% if 'tất cả' in q
          or 'all camera' in q
          or 'camera nào' in q
          or 'những camera' in q
          or 'các camera' in q
          or 'which cameras' in q
          or 'check all' in q
          or 'mọi camera' in q %}
        false
      {% else %}
        true
      {% endif %}
- variables:
    single_attachment: >-
      {% if final_single_camera %}
        {
          "media_content_id": "media-source://camera/{{ final_single_camera }}",
          "media_content_type": "application/vnd.apple.mpegurl",
          "metadata": {
            "title": "{{ state_attr(final_single_camera, 'friendly_name') or final_single_camera }}",
            "thumbnail": "/api/camera_proxy/{{ final_single_camera }}",
            "media_class": "video"
          }
        }
      {% else %}
        {}
      {% endif %}

    all_attachments: >-
      {% set ns = namespace(items=[]) %}
      {% for cam in all_cameras %}
        {% if states(cam) is not none %}
          {% set name = state_attr(cam, 'friendly_name') or cam %}
          {% set item = {
            'media_content_id': 'media-source://camera/' ~ cam,
            'media_content_type': 'application/vnd.apple.mpegurl',
            'metadata': {
              'title': name,
              'thumbnail': '/api/camera_proxy/' ~ cam,
              'media_class': 'video'
            }
          } %}
          {% set ns.items = ns.items + [item] %}
        {% endif %}
      {% endfor %}
      {{ ns.items }}

    camera_count: '{{ all_cameras | length }}'
- variables:
    final_prompt: "{{ system_prompt\n   | replace('{camera_list}', camera_list_text)\n   | replace('{user_question}', user_question) }}\n"
- choose:
  - conditions:
    - condition: template
      value_template: '{{ not ai_task_entity }}'
    sequence:
    - action: ai_task.generate_data
      data:
        task_name: Smart Camera Analysis
        instructions: '{{ final_prompt }}'
        attachments: >-
          {% if use_single_camera and final_single_camera %}
            {{ [single_attachment] }}
          {% else %}
            {{ all_attachments }}
          {% endif %}
        structure:
          overview:
            description: Short status of all cameras
            required: true
            selector:
              text: {}
          cameras_with_people:
            description: List of cameras with people
            required: true
            selector:
              text: {}
          cameras_no_people:
            description: List of cameras without people
            required: true
            selector:
              text: {}
          cameras_error:
            description: List of cameras with errors
            required: true
            selector:
              text: {}
          summary:
            description: One sentence summary in Vietnamese
            required: true
            selector:
              text: {}
      response_variable: ai_result
  - conditions:
    - condition: template
      value_template: '{{ ai_task_entity is not none }}'
    sequence:
    - action: ai_task.generate_data
      data:
        entity_id: '{{ ai_task_entity }}'
        task_name: Smart Camera Analysis
        instructions: '{{ final_prompt }}'
        attachments: >-
          {% if use_single_camera and final_single_camera %}
            {{ [single_attachment] }}
          {% else %}
            {{ all_attachments }}
          {% endif %}
        structure:
          overview:
            description: Short status of all cameras
            required: true
            selector:
              text: {}
          cameras_with_people:
            description: List of cameras with people
            required: true
            selector:
              text: {}
          cameras_no_people:
            description: List of cameras without people
            required: true
            selector:
              text: {}
          cameras_error:
            description: List of cameras with errors
            required: true
            selector:
              text: {}
          summary:
            description: One sentence summary in Vietnamese
            required: true
            selector:
              text: {}
      response_variable: ai_result
- variables:
    response:
      mode: '{{ "single" if use_single_camera else "multi" }}'
      camera_count: '{{ camera_count }}'
      selected_camera: '{{ final_single_camera }}'
      camera_name: '{{ state_attr(final_single_camera, "friendly_name") if final_single_camera else "" }}'
      matched_camera_from_friendly: '{{ matched_camera_from_friendly }}'
      matched_camera_from_alias: '{{ matched_camera_from_alias }}'
      guessed_camera_smart: '{{ guessed_camera_smart }}'
      data: '{{ ai_result.data }}'
- stop: ''
  response_variable: response
